#!perl -w
# script to remove odd cudaXX functions from clang generated PTX
use strict;
use warnings;
use Getopt::Std;

use vars qw/$opt_c/;

sub usage()
{
  print STDERR<<EOF;
Usage: $0 [options] file(s)
 Options:
  -c - generate map of CUDA runtime functions
EOF
  exit(8);
}

sub gen_crt {
  my($str, %names);
  while( $str = <> ) {
    chomp $str;
    if ( $str =~ /CUDARTAPI\s+([^\(]+)\s*\(/ ) {
      $names{$1}++;
      next;
    }
  }
  # dump in perl format
  foreach my $n ( sort keys %names ) {
    printf(" %s => 1,\n", $n);
  }
}

# generated with -c option
my %cfs = (
 cudaArrayGetInfo => 1,
 cudaArrayGetMemoryRequirements => 1,
 cudaArrayGetPlane => 1,
 cudaArrayGetSparseProperties => 1,
 cudaChooseDevice => 1,
 cudaCreateChannelDesc => 1,
 cudaCreateSurfaceObject => 1,
 cudaCreateTextureObject => 1,
 cudaCtxResetPersistingL2Cache => 1,
 cudaDestroyExternalMemory => 1,
 cudaDestroyExternalSemaphore => 1,
 cudaDestroySurfaceObject => 1,
 cudaDestroyTextureObject => 1,
 cudaDevResourceGenerateDesc => 1,
 cudaDevSmResourceSplit => 1,
 cudaDevSmResourceSplitByCount => 1,
 cudaDeviceCanAccessPeer => 1,
 cudaDeviceDisablePeerAccess => 1,
 cudaDeviceEnablePeerAccess => 1,
 cudaDeviceFlushGPUDirectRDMAWrites => 1,
 cudaDeviceGetAttribute => 1,
 cudaDeviceGetByPCIBusId => 1,
 cudaDeviceGetCacheConfig => 1,
 cudaDeviceGetDefaultMemPool => 1,
 cudaDeviceGetDevResource => 1,
 cudaDeviceGetExecutionCtx => 1,
 cudaDeviceGetGraphMemAttribute => 1,
 cudaDeviceGetHostAtomicCapabilities => 1,
 cudaDeviceGetLimit => 1,
 cudaDeviceGetMemPool => 1,
 cudaDeviceGetNvSciSyncAttributes => 1,
 cudaDeviceGetP2PAtomicCapabilities => 1,
 cudaDeviceGetP2PAttribute => 1,
 cudaDeviceGetPCIBusId => 1,
 cudaDeviceGetSharedMemConfig => 1,
 cudaDeviceGetStreamPriorityRange => 1,
 cudaDeviceGetTexture1DLinearMaxWidth => 1,
 cudaDeviceGraphMemTrim => 1,
 cudaDeviceRegisterAsyncNotification => 1,
 cudaDeviceReset => 1,
 cudaDeviceSetCacheConfig => 1,
 cudaDeviceSetGraphMemAttribute => 1,
 cudaDeviceSetLimit => 1,
 cudaDeviceSetMemPool => 1,
 cudaDeviceSetSharedMemConfig => 1,
 cudaDeviceSynchronize => 1,
 cudaDeviceUnregisterAsyncNotification => 1,
 cudaDriverGetVersion => 1,
 cudaEventCreate => 1,
 cudaEventCreateWithFlags => 1,
 cudaEventDestroy => 1,
 cudaEventElapsedTime => 1,
 cudaEventQuery => 1,
 cudaEventRecord => 1,
 cudaEventRecordWithFlags => 1,
 cudaEventSynchronize => 1,
 cudaExecutionCtxDestroy => 1,
 cudaExecutionCtxGetDevResource => 1,
 cudaExecutionCtxGetDevice => 1,
 cudaExecutionCtxGetId => 1,
 cudaExecutionCtxRecordEvent => 1,
 cudaExecutionCtxStreamCreate => 1,
 cudaExecutionCtxSynchronize => 1,
 cudaExecutionCtxWaitEvent => 1,
 cudaExternalMemoryGetMappedBuffer => 1,
 cudaExternalMemoryGetMappedMipmappedArray => 1,
 cudaFree => 1,
 cudaFreeArray => 1,
 cudaFreeAsync => 1,
 cudaFreeHost => 1,
 cudaFreeMipmappedArray => 1,
 cudaFuncGetAttributes => 1,
 cudaFuncGetName => 1,
 cudaFuncGetParamInfo => 1,
 cudaFuncSetAttribute => 1,
 cudaFuncSetCacheConfig => 1,
 cudaFuncSetSharedMemConfig => 1,
 cudaGetChannelDesc => 1,
 cudaGetDevice => 1,
 cudaGetDeviceCount => 1,
 cudaGetDeviceFlags => 1,
 cudaGetDeviceProperties => 1,
 cudaGetDriverEntryPoint => 1,
 cudaGetDriverEntryPointByVersion => 1,
 cudaGetErrorName => 1,
 cudaGetErrorString => 1,
 cudaGetExportTable => 1,
 cudaGetFuncBySymbol => 1,
 cudaGetKernel => 1,
 cudaGetLastError => 1,
 cudaGetMipmappedArrayLevel => 1,
 cudaGetSurfaceObjectResourceDesc => 1,
 cudaGetSymbolAddress => 1,
 cudaGetSymbolSize => 1,
 cudaGetTextureObjectResourceDesc => 1,
 cudaGetTextureObjectResourceViewDesc => 1,
 cudaGetTextureObjectTextureDesc => 1,
 cudaGraphAddChildGraphNode => 1,
 cudaGraphAddDependencies => 1,
 cudaGraphAddEmptyNode => 1,
 cudaGraphAddEventRecordNode => 1,
 cudaGraphAddEventWaitNode => 1,
 cudaGraphAddExternalSemaphoresSignalNode => 1,
 cudaGraphAddExternalSemaphoresWaitNode => 1,
 cudaGraphAddHostNode => 1,
 cudaGraphAddKernelNode => 1,
 cudaGraphAddMemAllocNode => 1,
 cudaGraphAddMemFreeNode => 1,
 cudaGraphAddMemcpyNode => 1,
 cudaGraphAddMemcpyNode1D => 1,
 cudaGraphAddMemcpyNodeFromSymbol => 1,
 cudaGraphAddMemcpyNodeToSymbol => 1,
 cudaGraphAddMemsetNode => 1,
 cudaGraphAddNode => 1,
 cudaGraphChildGraphNodeGetGraph => 1,
 cudaGraphClone => 1,
 cudaGraphConditionalHandleCreate => 1,
 cudaGraphConditionalHandleCreate_v2 => 1,
 cudaGraphCreate => 1,
 cudaGraphDebugDotPrint => 1,
 cudaGraphDestroy => 1,
 cudaGraphDestroyNode => 1,
 cudaGraphEventRecordNodeGetEvent => 1,
 cudaGraphEventRecordNodeSetEvent => 1,
 cudaGraphEventWaitNodeGetEvent => 1,
 cudaGraphEventWaitNodeSetEvent => 1,
 cudaGraphExecChildGraphNodeSetParams => 1,
 cudaGraphExecDestroy => 1,
 cudaGraphExecEventRecordNodeSetEvent => 1,
 cudaGraphExecEventWaitNodeSetEvent => 1,
 cudaGraphExecExternalSemaphoresSignalNodeSetParams => 1,
 cudaGraphExecExternalSemaphoresWaitNodeSetParams => 1,
 cudaGraphExecGetFlags => 1,
 cudaGraphExecGetId => 1,
 cudaGraphExecHostNodeSetParams => 1,
 cudaGraphExecKernelNodeSetParams => 1,
 cudaGraphExecMemcpyNodeSetParams => 1,
 cudaGraphExecMemcpyNodeSetParams1D => 1,
 cudaGraphExecMemcpyNodeSetParamsFromSymbol => 1,
 cudaGraphExecMemcpyNodeSetParamsToSymbol => 1,
 cudaGraphExecMemsetNodeSetParams => 1,
 cudaGraphExecNodeSetParams => 1,
 cudaGraphExecUpdate => 1,
 cudaGraphExternalSemaphoresSignalNodeGetParams => 1,
 cudaGraphExternalSemaphoresSignalNodeSetParams => 1,
 cudaGraphExternalSemaphoresWaitNodeGetParams => 1,
 cudaGraphExternalSemaphoresWaitNodeSetParams => 1,
 cudaGraphGetEdges => 1,
 cudaGraphGetId => 1,
 cudaGraphGetNodes => 1,
 cudaGraphGetRootNodes => 1,
 cudaGraphHostNodeGetParams => 1,
 cudaGraphHostNodeSetParams => 1,
 cudaGraphInstantiate => 1,
 cudaGraphInstantiateWithFlags => 1,
 cudaGraphInstantiateWithParams => 1,
 cudaGraphKernelNodeCopyAttributes => 1,
 cudaGraphKernelNodeGetAttribute => 1,
 cudaGraphKernelNodeGetParams => 1,
 cudaGraphKernelNodeSetAttribute => 1,
 cudaGraphKernelNodeSetParams => 1,
 cudaGraphLaunch => 1,
 cudaGraphMemAllocNodeGetParams => 1,
 cudaGraphMemFreeNodeGetParams => 1,
 cudaGraphMemcpyNodeGetParams => 1,
 cudaGraphMemcpyNodeSetParams => 1,
 cudaGraphMemcpyNodeSetParams1D => 1,
 cudaGraphMemcpyNodeSetParamsFromSymbol => 1,
 cudaGraphMemcpyNodeSetParamsToSymbol => 1,
 cudaGraphMemsetNodeGetParams => 1,
 cudaGraphMemsetNodeSetParams => 1,
 cudaGraphNodeFindInClone => 1,
 cudaGraphNodeGetContainingGraph => 1,
 cudaGraphNodeGetDependencies => 1,
 cudaGraphNodeGetDependentNodes => 1,
 cudaGraphNodeGetEnabled => 1,
 cudaGraphNodeGetLocalId => 1,
 cudaGraphNodeGetToolsId => 1,
 cudaGraphNodeGetType => 1,
 cudaGraphNodeSetEnabled => 1,
 cudaGraphNodeSetParams => 1,
 cudaGraphReleaseUserObject => 1,
 cudaGraphRemoveDependencies => 1,
 cudaGraphRetainUserObject => 1,
 cudaGraphUpload => 1,
 cudaGraphicsMapResources => 1,
 cudaGraphicsResourceGetMappedMipmappedArray => 1,
 cudaGraphicsResourceGetMappedPointer => 1,
 cudaGraphicsResourceSetMapFlags => 1,
 cudaGraphicsSubResourceGetMappedArray => 1,
 cudaGraphicsUnmapResources => 1,
 cudaGraphicsUnregisterResource => 1,
 cudaGreenCtxCreate => 1,
 cudaHostAlloc => 1,
 cudaHostGetDevicePointer => 1,
 cudaHostGetFlags => 1,
 cudaHostRegister => 1,
 cudaHostUnregister => 1,
 cudaImportExternalMemory => 1,
 cudaImportExternalSemaphore => 1,
 cudaInitDevice => 1,
 cudaIpcCloseMemHandle => 1,
 cudaIpcGetEventHandle => 1,
 cudaIpcGetMemHandle => 1,
 cudaIpcOpenEventHandle => 1,
 cudaIpcOpenMemHandle => 1,
 cudaKernelSetAttributeForDevice => 1,
 cudaLaunchCooperativeKernel => 1,
 cudaLaunchHostFunc => 1,
 cudaLaunchKernel => 1,
 cudaLaunchKernelExC => 1,
 cudaLibraryEnumerateKernels => 1,
 cudaLibraryGetGlobal => 1,
 cudaLibraryGetKernel => 1,
 cudaLibraryGetKernelCount => 1,
 cudaLibraryGetManaged => 1,
 cudaLibraryGetUnifiedFunction => 1,
 cudaLibraryLoadData => 1,
 cudaLibraryLoadFromFile => 1,
 cudaLibraryUnload => 1,
 cudaLogsCurrent => 1,
 cudaLogsDumpToFile => 1,
 cudaLogsDumpToMemory => 1,
 cudaLogsRegisterCallback => 1,
 cudaLogsUnregisterCallback => 1,
 cudaMalloc => 1,
 cudaMalloc3D => 1,
 cudaMalloc3DArray => 1,
 cudaMallocArray => 1,
 cudaMallocAsync => 1,
 cudaMallocFromPoolAsync => 1,
 cudaMallocHost => 1,
 cudaMallocManaged => 1,
 cudaMallocMipmappedArray => 1,
 cudaMallocPitch => 1,
 cudaMemAdvise => 1,
 cudaMemDiscardAndPrefetchBatchAsync => 1,
 cudaMemDiscardBatchAsync => 1,
 cudaMemGetDefaultMemPool => 1,
 cudaMemGetInfo => 1,
 cudaMemGetMemPool => 1,
 cudaMemPoolCreate => 1,
 cudaMemPoolDestroy => 1,
 cudaMemPoolExportPointer => 1,
 cudaMemPoolExportToShareableHandle => 1,
 cudaMemPoolGetAccess => 1,
 cudaMemPoolGetAttribute => 1,
 cudaMemPoolImportFromShareableHandle => 1,
 cudaMemPoolImportPointer => 1,
 cudaMemPoolSetAccess => 1,
 cudaMemPoolSetAttribute => 1,
 cudaMemPoolTrimTo => 1,
 cudaMemPrefetchAsync => 1,
 cudaMemPrefetchBatchAsync => 1,
 cudaMemRangeGetAttribute => 1,
 cudaMemRangeGetAttributes => 1,
 cudaMemSetMemPool => 1,
 cudaMemcpy => 1,
 cudaMemcpy2D => 1,
 cudaMemcpy2DArrayToArray => 1,
 cudaMemcpy2DAsync => 1,
 cudaMemcpy2DFromArray => 1,
 cudaMemcpy2DFromArrayAsync => 1,
 cudaMemcpy2DToArray => 1,
 cudaMemcpy2DToArrayAsync => 1,
 cudaMemcpy3D => 1,
 cudaMemcpy3DAsync => 1,
 cudaMemcpy3DBatchAsync => 1,
 cudaMemcpy3DPeer => 1,
 cudaMemcpy3DPeerAsync => 1,
 cudaMemcpyArrayToArray => 1,
 cudaMemcpyAsync => 1,
 cudaMemcpyBatchAsync => 1,
 cudaMemcpyFromArray => 1,
 cudaMemcpyFromArrayAsync => 1,
 cudaMemcpyFromSymbol => 1,
 cudaMemcpyFromSymbolAsync => 1,
 cudaMemcpyPeer => 1,
 cudaMemcpyPeerAsync => 1,
 cudaMemcpyToArray => 1,
 cudaMemcpyToArrayAsync => 1,
 cudaMemcpyToSymbol => 1,
 cudaMemcpyToSymbolAsync => 1,
 cudaMemset => 1,
 cudaMemset2D => 1,
 cudaMemset2DAsync => 1,
 cudaMemset3D => 1,
 cudaMemset3DAsync => 1,
 cudaMemsetAsync => 1,
 cudaMipmappedArrayGetMemoryRequirements => 1,
 cudaMipmappedArrayGetSparseProperties => 1,
 cudaOccupancyAvailableDynamicSMemPerBlock => 1,
 cudaOccupancyMaxActiveBlocksPerMultiprocessor => 1,
 cudaOccupancyMaxActiveBlocksPerMultiprocessorWithFlags => 1,
 cudaOccupancyMaxActiveClusters => 1,
 cudaOccupancyMaxPotentialClusterSize => 1,
 cudaPeekAtLastError => 1,
 cudaPointerGetAttributes => 1,
 cudaRuntimeGetVersion => 1,
 cudaSetDevice => 1,
 cudaSetDeviceFlags => 1,
 cudaSetValidDevices => 1,
 cudaSignalExternalSemaphoresAsync => 1,
 cudaStreamAddCallback => 1,
 cudaStreamAttachMemAsync => 1,
 cudaStreamBeginCapture => 1,
 cudaStreamBeginCaptureToGraph => 1,
 cudaStreamCopyAttributes => 1,
 cudaStreamCreate => 1,
 cudaStreamCreateWithFlags => 1,
 cudaStreamCreateWithPriority => 1,
 cudaStreamDestroy => 1,
 cudaStreamEndCapture => 1,
 cudaStreamGetAttribute => 1,
 cudaStreamGetCaptureInfo => 1,
 cudaStreamGetDevResource => 1,
 cudaStreamGetDevice => 1,
 cudaStreamGetFlags => 1,
 cudaStreamGetId => 1,
 cudaStreamGetPriority => 1,
 cudaStreamIsCapturing => 1,
 cudaStreamQuery => 1,
 cudaStreamSetAttribute => 1,
 cudaStreamSynchronize => 1,
 cudaStreamUpdateCaptureDependencies => 1,
 cudaStreamWaitEvent => 1,
 cudaThreadExchangeStreamCaptureMode => 1,
 cudaUserObjectCreate => 1,
 cudaUserObjectRelease => 1,
 cudaUserObjectRetain => 1,
 cudaWaitExternalSemaphoresAsync => 1,
);

sub process {
  my($str);
  my $status = 0;
  while( $str = <> ) {
    if ( !$status ) {
      if ( $str =~ /\.weak\s+\.func\s+.*(cuda\w+)/ ) {
        if ( exists $cfs{$1} ) {
          $status = 1;
          next;
        }
      }
      print $str;
      next;
    }
    # check -- End function
    if ( $str =~ /-- End function/ ) {
      $status = 2;
      next;
    }
    if ( 2 == $status && $str =~ /\}/ ) {
      $status = 0;
      next;
    }
  }
}

# main
my $status = getopts("c");
usage() if ( !$status );
if ( 1 == $#ARGV ) {
  printf("where is arg?\n");
  exit(5);
}
if ( defined $opt_c ) {
  gen_crt();
} else {
  process();
}
